ILICHECK-113 refactor client
GeoWerkstatt/interlis-check-service pull request #118
Opened 2022-06-15 10:46 UTC by MiraGeowerkstatt

2022-06-15 11:19 UTC, danjov approved these changes
lgtm

2022-06-15 12:17 UTC, flenny requested changes
REQ: Beim Design hats einiges durchgeschüttelt 😅 Was mir auf die Schnelle aufgefallen ist: Upload-Icon falsch positioniert, _Validieren_ Button wird beim Validieren nicht mehr ausgeblendet, _Fehler_/_Keine Fehler_-Text wird nicht mehr eingefärbt, Quicknotes Text und Icons liegen übereinander, Nutzungsbestimmungen Text falsch ausgerichet, Banner am falschen Ort.
![image](https://user-images.githubusercontent.com/1365121/173824808-ace5d7e2-5051-4684-b64a-f60ca6aba067.png)

2022-06-15 12:18 UTC, MiraGeowerkstatt commented
> 

Oh no! Ich hab natürlich nur ohne zusätzlich Assets getestet :( 

Ich schaus an!

2022-06-15 13:08 UTC, MiraGeowerkstatt commented
> > 
> 
> Oh no! Ich hab natürlich nur ohne zusätzlich Assets getestet :(
> 
> Ich schaus an!

Die ganzen Verschiebungen von Text und auch dass nicht richtig eingefärbt wurde ist bei mir gar nicht aufgetreten 🤔 .
Nur das Banner und der Button der nicht ausgeblendet wurde und falsche Farbe hatte, ausserdem  noch Icons die kleiner waren als normal . Es ist irgendein CSS Spezifizitäts-Ding, dass die custom classes von den bootstrap Standardklassen überschrieben werden, was eigentlich nicht sein dürfte... Habe die Spezifizität der Klassen jetzt erhöht.

2022-06-15 13:32 UTC, flenny commented
> > > 
> > 
> > 
> > Oh no! Ich hab natürlich nur ohne zusätzlich Assets getestet :(
> > Ich schaus an!
> 
> Die ganzen Verschiebungen von Text und auch dass nicht richtig eingefärbt wurde ist bei mir gar nicht aufgetreten 🤔 . Nur das Banner und der Button der nicht ausgeblendet wurde und falsche Farbe hatte, ausserdem noch Icons die kleiner waren als normal . Es ist irgendein CSS Spezifizitäts-Ding, dass die custom classes von den bootstrap Standardklassen überschrieben werden, was eigentlich nicht sein dürfte... Habe die Spezifizität der Klassen jetzt erhöht.

Hab das Problem mit verschiedenen Browsern. Wenn ich zurück auf den [releases/beta/rest-api](https://github.com/GeoWerkstatt/interlis-check-service/tree/releases/beta/rest-api) branch gehe, ist wieder alles fein. Ctrl+F5 ? Oder kurz 🤙🏼 ?

2022-06-15 13:34 UTC, MiraGeowerkstatt commented
> > > > 
> > > 
> > > 
> > > Oh no! Ich hab natürlich nur ohne zusätzlich Assets getestet :(
> > > Ich schaus an!
> > 
> > 
> > Die ganzen Verschiebungen von Text und auch dass nicht richtig eingefärbt wurde ist bei mir gar nicht aufgetreten 🤔 . Nur das Banner und der Button der nicht ausgeblendet wurde und falsche Farbe hatte, ausserdem noch Icons die kleiner waren als normal . Es ist irgendein CSS Spezifizitäts-Ding, dass die custom classes von den bootstrap Standardklassen überschrieben werden, was eigentlich nicht sein dürfte... Habe die Spezifizität der Klassen jetzt erhöht.
> 
> Hab das Problem mit verschiedenen Browsern. Wenn ich zurück auf den [releases/beta/rest-api](https://github.com/GeoWerkstatt/interlis-check-service/tree/releases/beta/rest-api) branch gehe, ist wieder alles fein. Ctrl+F5 ? Oder kurz 🤙🏼 ?

Sind die Probleme denn immer noch da?

2022-06-15 13:35 UTC, flenny commented
Ja 💩

2022-06-16 06:25 UTC, flenny approved these changes

2022-06-16 06:29 UTC, merged