add dedicated changelog
GeoWerkstatt/interlis-check-service pull request #130
Opened 2022-09-19 15:39 UTC by olivergrimm

2022-09-20 07:49 UTC, flenny requested changes

2022-09-20 07:49 UTC, flenny commented on changelog.md
> +- Support validation against local catalogue files
Q: Stimmt das so?

2022-09-20 07:49 UTC, flenny commented on changelog.md
> +- Improved error logs in the case of unaccessible logfiles
PP

```suggestion
- Improved error logs in the case of unavailable logfiles
```

2022-09-20 07:49 UTC, flenny commented on changelog.md
> +- dockerised
Q: Fehlt da noch was?

2022-09-20 12:29 UTC, olivergrimm commented on changelog.md
> +- Support validation against local catalogue files
naja, 'local' darf halt nicht missverstanden werden.

2022-09-20 12:34 UTC, olivergrimm commented on changelog.md
> +- dockerised
habe noch einen Punkt ergänzt. Die übrigen sind m.E. nicht relevant

2022-09-22 09:10 UTC, flenny approved these changes

2022-09-22 09:11 UTC, merged