Visualize validation log in UI
GeoWerkstatt/interlis-check-service pull request #185
Opened 2024-03-21 13:27 UTC by domi-b

- Neuer API-Endpunkt `/api/v1/download/json?jobId=...` für Daten des XTF-Logfiles als JSON.
- Validierungen werden neu mit dem Flag `--verbose` durchgeführt.
  - Der Name und die Definition der Constraints werden dadurch im Log aufgeführt (auch bei angepassten Fehlermeldungen).

2024-03-22 10:31 UTC, danjov requested changes
Q: Brauchts einen Eintrag im CHANGELOG?

2024-03-22 10:31 UTC, danjov commented on src/ILICheck.Web/ClientApp/src/logHierarchy.js
> +import groupBy from "object.groupby";
REQ Generell: Alles Funktionen sauber dokumentieren.

2024-03-22 10:31 UTC, danjov commented on src/ILICheck.Web/ClientApp/src/logHierarchy.js
> +  for (const entry of entries) {
PP: Um den Code verständlicher zu machen, würde ich explizitere Variablennamen verwenden. Hier z.B. `logEntry` und `logEntries`. Das würde ich generell im ganzen File durchziehen.

2024-03-22 10:31 UTC, danjov commented on src/ILICheck.Web/ClientApp/src/logHierarchy.js
> +      for (const [name, infoPattern] of constraintPatterns) {
PP: Um den Code verständlicher zu machen, würde ich explizitere Variablennamen verwenden. Hier z.B. `patternName` und `pattern`. Der Zusatz `info` beim Pattern ist für mich nicht ganz klar, da sonst keine anderen `pattern`-Typen im Code vorkommen.

2024-03-22 10:31 UTC, danjov commented on src/ILICheck.Web/XtfLog/XtfLogParser.cs
> +        {
REQ: XML-Doku hinzufügen

2024-03-22 13:21 UTC, Philippluca reviewed
Nur Comments, da ich in den Urlaub gehe. Es gibt REQs. Leider konnte ich die Dev-Umbebung bei mir nicht starten.
REQ: Im Changelog über `--verbose` Flag aufklären.

2024-03-22 13:21 UTC, Philippluca commented on src/ILICheck.Web/ClientApp/src/logDisplay.js
> +export const LogDisplay = ({ statusData }) => {
REQ: Die 2 Komponenten dokumentieren.

2024-03-22 13:21 UTC, Philippluca commented on src/ILICheck.Web/ClientApp/src/logDisplayEntry.js
> +  const [open, setOpen] = useState(false);
PP: `collapsed` oder `showChildren`

2024-03-22 13:21 UTC, Philippluca commented on src/ILICheck.Web/ClientApp/src/logHierarchy.js
> +// e.g. "Custom message ModelA.TopicA.ClassA.ConstraintName (ILI syntax)" will result in "Custom message"
Q: Gibt es JS Doc oder sowas? Falls möglich mehr als einfache Kommentare verwenden.

2024-03-22 13:21 UTC, Philippluca commented on src/ILICheck.Web/ClientApp/src/logHierarchy.js
> +      for (const [name, infoPattern] of constraintPatterns) {
ev. lässt sich die Funktion auch noch etwas aufstückeln.

2024-03-22 13:21 UTC, Philippluca commented on src/ILICheck.Web/ClientApp/src/logHierarchy.js
> +function addOrReplaceLogEntry(entries, contraintType, constraintName, entry) {
PP/Q: `addOrReplace..` hat etwas OOP Charakter. Lässt sich das Funktionaler lösen & benennen? Hint: Reduce.

2024-03-22 13:21 UTC, Philippluca commented on src/ILICheck.Web/ClientApp/src/logHierarchy.js
> +        }
PP: Reduce und Auslagern

2024-03-25 14:19 UTC, domi-b commented
Werden die Version und das Datum im Changelog manuell erfasst?
Und falls ja, wie finde ich die Versionsnummer, mit der das released wird?

2024-03-25 15:23 UTC, danjov submitted a review, later dismissed

2024-03-25 15:30 UTC, danjov approved these changes

2024-03-25 15:35 UTC, merged